### model
model_name_or_path: /home/share/models/Qwen2.5-1.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: "magicoder-[0:5000]"
template: qwen
cutoff_len: 32768
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2.5-1.5B-Instruct/magicoder-[0:5000]
logging_steps: 1
save_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 40
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
